# Netlify configuration file for Klassik Asaeda

[build]
  publish = "/"
  command = "echo 'No build command required'"

# Handle redirects for clean URLs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# Headers to improve security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'"

# Form handling configuration
[forms]
  # Main checkout form
  [forms.checkout]
    name = "checkout"
    
    [forms.checkout.fields]
      [forms.checkout.fields.name]
        required = true
      
      [forms.checkout.fields.email]
        required = true
      
      [forms.checkout.fields.phone]
        required = false
      
      [forms.checkout.fields.order_details]
        required = true
      
      [forms.checkout.fields.order_total]
        required = true

# Environment variables for the site
[context.production.environment]
  SITE_NAME = "Klassik Asaeda"
